/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlinecarrentalsystem;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.concurrent.TimeUnit;
/**
 *
 * @author User
 */
public class Admin_ManageBooking1 extends javax.swing.JFrame {
private Booking booking;
    /**
     * Creates new form Admin_ManageBooking1
     */
    public Admin_ManageBooking1() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(204,204,255));

        booking = new Booking();
        
        readPendingBookingTable();
        readBookingTable();
        
        //search no result not visible
        noResult.setVisible(false);
        noResult1.setVisible(false);
        days.setVisible(false);
        pendingBookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            noResult1.setVisible(false);
            int  row = pendingBookingTable.rowAtPoint(evt.getPoint());
            Object id = pendingBookingTable.getValueAt( row, 0 );
            booking.setBookingID(id+"");
            if(booking.searchBooking()){
                bookID1.setText(booking.getBookingID());
                carID1.setText(booking.getCarID());
                custID1.setText(booking.getCustomerID());
                dateOut1.setText(booking.getOutDate());
                dateReturn1.setText(booking.getReturnDate());

                Car car = new Car(booking.getCarID());
                model1.setText(car.getModel());
                color1.setText(car.getColor());
                plateNo1.setText(car.getPlateNo());

                Customer cust = new Customer(booking.getCustomerID());
                custName1.setText(cust.getCustomerName());
                ic.setText(cust.getCustomerIC());
                email1.setText(cust.getCustomerEmail());
                contactNo1.setText(cust.getCustomerContact());

            }  else {
                JOptionPane.showMessageDialog(null, "Selected row doesn't contain any record"); 
            }
          }
    });
        bookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            noResult.setVisible(false);
            SimpleDateFormat df = new SimpleDateFormat();
            int  row = bookingTable.rowAtPoint(evt.getPoint());
            Object id = bookingTable.getValueAt( row, 0 );
            booking.setBookingID(id+"");
            if(booking.searchBooking()){
                bookID.setText(booking.getBookingID());
                carID.setText(booking.getCarID());
                custID.setText(booking.getCustomerID());
                try {
                    dateOut.setDate(df.parse(booking.getOutDate()));
                    dateReturn.setDate(df.parse(booking.getReturnDate()));
                } catch(ParseException pe) {
                    pe.printStackTrace();
                }
                
                Car car = new Car(booking.getCarID());
                model.setText(car.getModel());
                color.setText(car.getColor());
                plateNo.setText(car.getPlateNo());

                Customer cust = new Customer(booking.getCustomerID());
                custName.setText(cust.getCustomerName());
                IC.setText(cust.getCustomerIC());
                email.setText(cust.getCustomerEmail());
                contactNo.setText(cust.getCustomerContact());

            }  else {
                JOptionPane.showMessageDialog(null, "Selected row doesn't contain any record"); 
            }
          }
    });
    }
                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingBookingTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        SearchTxt1 = new javax.swing.JTextField();
        SearchBtn1 = new javax.swing.JButton();
        noResult1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bookID1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlab1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlab11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        model1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        carID1 = new javax.swing.JTextField();
        approveBtn = new javax.swing.JButton();
        declineBtn = new javax.swing.JButton();
        ic = new javax.swing.JTextField();
        custName1 = new javax.swing.JTextField();
        contactNo1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        custID1 = new javax.swing.JTextField();
        dateReturn1 = new javax.swing.JTextField();
        dateOut1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        plateNo1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        color1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchTxt = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        noResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        custID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlab = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlab10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateOut = new com.toedter.calendar.JDateChooser();
        dateReturn = new com.toedter.calendar.JDateChooser();
        carID = new javax.swing.JTextField();
        bookID = new javax.swing.JTextField();
        custName = new javax.swing.JTextField();
        IC = new javax.swing.JTextField();
        contactNo = new javax.swing.JTextField();
        EditBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        plateNo = new javax.swing.JTextField();
        payPane = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        PCustName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        paymentLab = new javax.swing.JLabel();
        receiptBtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        PBookID = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        PDate = new javax.swing.JTextField();
        car = new javax.swing.JTextField();
        tax = new javax.swing.JTextField();
        deposit = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        totalPrice = new javax.swing.JTextField();
        paid = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        rentalDate = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        days = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        pendingBookingTable.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        pendingBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Car ID", "Customer ID", "Date Out", "Date Return"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pendingBookingTable);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel11.setText("Search by Booking ID or Customer ID:");

        SearchTxt1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        SearchTxt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        SearchTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxt1ActionPerformed(evt);
            }
        });

        SearchBtn1.setBackground(new java.awt.Color(102, 0, 255));
        SearchBtn1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        SearchBtn1.setForeground(new java.awt.Color(255, 255, 255));
        SearchBtn1.setText("Search");
        SearchBtn1.setBorder(null);
        SearchBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtn1ActionPerformed(evt);
            }
        });

        noResult1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        noResult1.setForeground(new java.awt.Color(255, 51, 51));
        noResult1.setText("No result found");

        jLabel12.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel12.setText("Booking ID: ");

        bookID1.setEditable(false);
        bookID1.setBackground(new java.awt.Color(204, 204, 255));
        bookID1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        bookID1.setBorder(null);
        bookID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookID1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel13.setText("Customer Name:");

        jLabel14.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel14.setText("IC no:");

        jLabel15.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel15.setText("Contact number: ");

        jlab1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jlab1.setText("Email: ");

        jLabel16.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel16.setText("Date Return:");

        jlab11.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jlab11.setText("Date Out:");

        jLabel18.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel18.setText("Car Model:");

        model1.setEditable(false);
        model1.setBackground(new java.awt.Color(204, 204, 255));
        model1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        model1.setBorder(null);
        model1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel19.setText("Car ID:");

        carID1.setEditable(false);
        carID1.setBackground(new java.awt.Color(204, 204, 255));
        carID1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        carID1.setBorder(null);
        carID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carID1ActionPerformed(evt);
            }
        });

        approveBtn.setBackground(new java.awt.Color(102, 0, 255));
        approveBtn.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        approveBtn.setForeground(new java.awt.Color(255, 255, 255));
        approveBtn.setText("Approve");
        approveBtn.setBorder(null);
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        declineBtn.setBackground(new java.awt.Color(255, 51, 51));
        declineBtn.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        declineBtn.setForeground(new java.awt.Color(255, 255, 255));
        declineBtn.setText("Decline");
        declineBtn.setBorder(null);
        declineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBtnActionPerformed(evt);
            }
        });

        ic.setEditable(false);
        ic.setBackground(new java.awt.Color(204, 204, 255));
        ic.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        ic.setBorder(null);
        ic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icActionPerformed(evt);
            }
        });

        custName1.setEditable(false);
        custName1.setBackground(new java.awt.Color(204, 204, 255));
        custName1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        custName1.setBorder(null);
        custName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custName1ActionPerformed(evt);
            }
        });

        contactNo1.setEditable(false);
        contactNo1.setBackground(new java.awt.Color(204, 204, 255));
        contactNo1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        contactNo1.setBorder(null);
        contactNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNo1ActionPerformed(evt);
            }
        });

        email1.setEditable(false);
        email1.setBackground(new java.awt.Color(204, 204, 255));
        email1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        email1.setBorder(null);
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel20.setText("Customer ID:");

        custID1.setEditable(false);
        custID1.setBackground(new java.awt.Color(204, 204, 255));
        custID1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        custID1.setBorder(null);
        custID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custID1ActionPerformed(evt);
            }
        });

        dateReturn1.setEditable(false);
        dateReturn1.setBackground(new java.awt.Color(204, 204, 255));
        dateReturn1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        dateReturn1.setBorder(null);
        dateReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateReturn1ActionPerformed(evt);
            }
        });

        dateOut1.setEditable(false);
        dateOut1.setBackground(new java.awt.Color(204, 204, 255));
        dateOut1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        dateOut1.setBorder(null);
        dateOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOut1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel22.setText("Plate no:");

        plateNo1.setEditable(false);
        plateNo1.setBackground(new java.awt.Color(204, 204, 255));
        plateNo1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        plateNo1.setBorder(null);
        plateNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateNo1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel23.setText("Car Color:");

        color1.setEditable(false);
        color1.setBackground(new java.awt.Color(204, 204, 255));
        color1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        color1.setBorder(null);
        color1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SearchTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(461, 461, 461))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noResult1)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jlab1)
                            .addComponent(jLabel14)
                            .addComponent(jlab11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(contactNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addComponent(ic, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(custName1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(email1)
                                .addComponent(bookID1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(dateOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(dateReturn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(color1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plateNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(custID1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(carID1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(56, 56, 56)
                                .addComponent(model1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(noResult1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(bookID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(custID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(custName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(model1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(plateNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(contactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlab1)
                                .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(carID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(dateReturn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlab11)
                        .addComponent(dateOut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pending Booking", jPanel1);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Car ID", "Customer ID", "Date Out", "Date Return"
            }
        ));
        jScrollPane2.setViewportView(bookingTable);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel1.setText("Search by Booking ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 236, -1));

        SearchTxt.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        SearchTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        SearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtActionPerformed(evt);
            }
        });
        jPanel2.add(SearchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 35, 114, -1));

        SearchBtn.setBackground(new java.awt.Color(102, 0, 255));
        SearchBtn.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchBtn.setText("Search");
        SearchBtn.setBorder(null);
        SearchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 36, 56, 22));

        noResult.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        noResult.setForeground(new java.awt.Color(255, 51, 51));
        noResult.setText("No result found");
        jPanel2.add(noResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel2.setText("Booking ID: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, -1, -1));

        email.setEditable(false);
        email.setBackground(new java.awt.Color(204, 204, 255));
        email.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, -1));

        jLabel4.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel4.setText("Customer Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, -1, -1));

        custID.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        custID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel2.add(custID, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, -1));

        jLabel5.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel5.setText("IC no:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 177, 144, -1));

        jLabel8.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel8.setText("Contact Number: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 221, -1, -1));

        jlab.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jlab.setText("Email: ");
        jPanel2.add(jlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 265, -1, -1));

        jLabel10.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel10.setText("Date return:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 87, -1));

        jlab10.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jlab10.setText("Date out:");
        jPanel2.add(jlab10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel6.setText("Car color:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 76, -1));

        model.setEditable(false);
        model.setBackground(new java.awt.Color(204, 204, 255));
        model.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        model.setBorder(null);
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });
        jPanel2.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 150, -1));

        jLabel9.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel9.setText("Car ID:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 133, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel3.setText("Customer ID:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 92, -1, -1));
        jPanel2.add(dateOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, -1));
        jPanel2.add(dateReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 140, -1));

        carID.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        carID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel2.add(carID, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 150, -1));

        bookID.setEditable(false);
        bookID.setBackground(new java.awt.Color(204, 204, 255));
        bookID.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        bookID.setBorder(null);
        bookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIDActionPerformed(evt);
            }
        });
        jPanel2.add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 92, 150, -1));

        custName.setEditable(false);
        custName.setBackground(new java.awt.Color(204, 204, 255));
        custName.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        custName.setBorder(null);
        custName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameActionPerformed(evt);
            }
        });
        jPanel2.add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, -1));

        IC.setEditable(false);
        IC.setBackground(new java.awt.Color(204, 204, 255));
        IC.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        IC.setBorder(null);
        IC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICActionPerformed(evt);
            }
        });
        jPanel2.add(IC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, -1));

        contactNo.setEditable(false);
        contactNo.setBackground(new java.awt.Color(204, 204, 255));
        contactNo.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        contactNo.setBorder(null);
        contactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoActionPerformed(evt);
            }
        });
        jPanel2.add(contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, -1));

        EditBtn.setBackground(new java.awt.Color(102, 0, 255));
        EditBtn.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(255, 255, 255));
        EditBtn.setText("Edit");
        EditBtn.setBorder(null);
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        jPanel2.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 81, 37));

        checkoutBtn.setBackground(new java.awt.Color(102, 0, 255));
        checkoutBtn.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setText("Pay");
        checkoutBtn.setBorder(null);
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });
        jPanel2.add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 81, 37));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 81, 37));

        jLabel17.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel17.setText("Car Model:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 177, 76, -1));

        jLabel21.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel21.setText("Plate no:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 76, -1));

        color.setEditable(false);
        color.setBackground(new java.awt.Color(204, 204, 255));
        color.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        color.setBorder(null);
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        jPanel2.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 150, -1));

        plateNo.setEditable(false);
        plateNo.setBackground(new java.awt.Color(204, 204, 255));
        plateNo.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        plateNo.setBorder(null);
        plateNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateNoActionPerformed(evt);
            }
        });
        jPanel2.add(plateNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 150, -1));

        payPane.setBackground(new java.awt.Color(232, 232, 247));

        jLabel29.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel29.setText("Customer Name:");

        PCustName.setEditable(false);
        PCustName.setBackground(new java.awt.Color(232, 232, 247));
        PCustName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        PCustName.setBorder(null);
        PCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCustNameActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(232, 232, 247));

        jLabel30.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel30.setText("Paid Value:");

        jLabel7.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel7.setText("Balance: ");

        paymentLab.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        paymentLab.setText("Payment");

        receiptBtn.setBackground(new java.awt.Color(102, 0, 255));
        receiptBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        receiptBtn.setForeground(new java.awt.Color(255, 255, 255));
        receiptBtn.setText("Generate Receipt");
        receiptBtn.setBorder(null);
        receiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptBtnActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel31.setText("Deposit :");

        PBookID.setEditable(false);
        PBookID.setBackground(new java.awt.Color(232, 232, 247));
        PBookID.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        PBookID.setBorder(null);
        PBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBookIDActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(232, 232, 247));

        jLabel33.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel33.setText("Subtotal: ");

        PDate.setEditable(false);
        PDate.setBackground(new java.awt.Color(232, 232, 247));
        PDate.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        PDate.setBorder(null);
        PDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDateActionPerformed(evt);
            }
        });

        car.setEditable(false);
        car.setBackground(new java.awt.Color(232, 232, 247));
        car.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        car.setBorder(null);
        car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carActionPerformed(evt);
            }
        });

        tax.setEditable(false);
        tax.setBackground(new java.awt.Color(232, 232, 247));
        tax.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        tax.setBorder(null);

        deposit.setEditable(false);
        deposit.setBackground(new java.awt.Color(232, 232, 247));
        deposit.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        deposit.setBorder(null);
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });

        subtotal.setEditable(false);
        subtotal.setBackground(new java.awt.Color(232, 232, 247));
        subtotal.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        subtotal.setBorder(null);
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        totalPrice.setEditable(false);
        totalPrice.setBackground(new java.awt.Color(232, 232, 247));
        totalPrice.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        totalPrice.setBorder(null);

        paid.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N

        balance.setEditable(false);
        balance.setBackground(new java.awt.Color(232, 232, 247));
        balance.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        balance.setBorder(null);

        jLabel34.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel34.setText("Booking ID: ");

        jLabel35.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel35.setText("Tax (10%): ");

        rentalDate.setEditable(false);
        rentalDate.setBackground(new java.awt.Color(232, 232, 247));
        rentalDate.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rentalDate.setBorder(null);
        rentalDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalDateActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel36.setText("Total Price:");

        jSeparator1.setBackground(new java.awt.Color(232, 232, 247));

        days.setEditable(false);
        days.setBackground(new java.awt.Color(241, 241, 255));
        days.setBorder(null);

        javax.swing.GroupLayout payPaneLayout = new javax.swing.GroupLayout(payPane);
        payPane.setLayout(payPaneLayout);
        payPaneLayout.setHorizontalGroup(
            payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPaneLayout.createSequentialGroup()
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payPaneLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(receiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(payPaneLayout.createSequentialGroup()
                            .addGap(332, 332, 332)
                            .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, payPaneLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, payPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, payPaneLayout.createSequentialGroup()
                                    .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(paid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(balance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(payPaneLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel36)
                                    .addGap(249, 249, 249)
                                    .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, payPaneLayout.createSequentialGroup()
                                    .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, payPaneLayout.createSequentialGroup()
                                                    .addComponent(car, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rentalDate))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, payPaneLayout.createSequentialGroup()
                                                    .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(payPaneLayout.createSequentialGroup()
                                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(PBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jLabel29))
                                                        .addComponent(paymentLab, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PDate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(days, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        payPaneLayout.setVerticalGroup(
            payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentLab))
                .addGap(15, 15, 15)
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(PBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(PCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(payPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(paid, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(payPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(receiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(payPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))))
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Booking Records", jPanel4);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jTextField2.setText("Manage Booking");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(593, 593, 593)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void readPendingBookingTable(){
        DefaultTableModel tableModel = (DefaultTableModel)pendingBookingTable.getModel();
        tableModel.setRowCount(0);        
        //read rows into table
        ArrayList<String> bookArray = booking.readBooking();
        for (String bookRecord:bookArray){
            String booking[] = bookRecord.split(";");
            if (booking[5].trim().toLowerCase().equals("processing")){
                    tableModel.insertRow(tableModel.getRowCount(), new Object[]{booking[0],booking[1],booking[2],booking[3],booking[4]});
            }
        }
    }
    
    private void readBookingTable(){
        DefaultTableModel tableModel = (DefaultTableModel)bookingTable.getModel();
        tableModel.setRowCount(0);        
        //read rows into table
        ArrayList<String> bookArray = booking.readBooking();
        for (String bookRecord:bookArray){
            String booking[] = bookRecord.split(";");
            if (booking[5].trim().toLowerCase().equals("approved")){
                    tableModel.insertRow(tableModel.getRowCount(), new Object[]{booking[0],booking[1],booking[2],booking[3],booking[4]});
            }
        }
    }
    
    private void PCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCustNameActionPerformed

    private void receiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptBtnActionPerformed
        // TODO add your handling code here:
        //display balance 
        double balancetxt = Double.parseDouble(paid.getText()) - Double.parseDouble(totalPrice.getText());
        balance.setText(balancetxt+"");
        
        //store payment record into payment.txt
        Payment payment = new Payment();
        ArrayList<String> paymentArray = new ArrayList<String>();
        paymentArray.add(payment.newPaymentID()+";"+PBookID.getText()+";"+totalPrice.getText()+";"+PDate.getText());
        payment.addPayment(paymentArray);
    }//GEN-LAST:event_receiptBtnActionPerformed

    private void PBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBookIDActionPerformed

    private void PDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDateActionPerformed

    private void carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carActionPerformed

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed

    private void rentalDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentalDateActionPerformed

    private void SearchTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxt1ActionPerformed

    private void SearchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtn1ActionPerformed
        // TODO add your handling code here:
        noResult1.setVisible(false);
        booking.setBookingID(SearchTxt1.getText());
        if(booking.searchBooking()){
            bookID1.setText(booking.getBookingID());
            carID1.setText(booking.getCarID());
            custID1.setText(booking.getCustomerID());
            dateOut1.setText(booking.getOutDate());
            dateReturn1.setText(booking.getReturnDate());
            
            Car car = new Car(booking.getCarID());
            model1.setText(car.getModel());
            color1.setText(car.getColor());
            plateNo1.setText(car.getPlateNo());
            
            Customer cust = new Customer(booking.getCustomerID());
            custName1.setText(cust.getCustomerName());
            ic.setText(cust.getCustomerIC());
            email1.setText(cust.getCustomerEmail());
            contactNo1.setText(cust.getCustomerContact());
            
        } 
        else{
            noResult1.setVisible(true);
        }
    }//GEN-LAST:event_SearchBtn1ActionPerformed

    private void bookID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookID1ActionPerformed

    private void model1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model1ActionPerformed

    private void carID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carID1ActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> bookArray = new ArrayList<String>();
        bookArray.add(bookID1.getText());
        bookArray.add(carID1.getText());
        bookArray.add(custID1.getText());
        bookArray.add(carID1.getText());
        bookArray.add(dateOut1.getText());
        bookArray.add(dateReturn1.getText());
        bookArray.add("approved");
        booking.modifyBooking(bookArray);
    }//GEN-LAST:event_approveBtnActionPerformed

    private void declineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> bookArray = new ArrayList<String>();
        bookArray.add(bookID1.getText());
        bookArray.add(carID1.getText());
        bookArray.add(custID1.getText());
        bookArray.add(carID1.getText());
        bookArray.add(dateOut1.getText());
        bookArray.add(dateReturn1.getText());
        bookArray.add("rejected");
        booking.modifyBooking(bookArray);
    }//GEN-LAST:event_declineBtnActionPerformed

    private void icActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icActionPerformed

    private void custName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custName1ActionPerformed

    private void contactNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNo1ActionPerformed

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxtActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        noResult.setVisible(false);
        booking.setBookingID(SearchTxt.getText());
        if(booking.searchBooking()){
            bookID.setText(booking.getBookingID());
            carID.setText(booking.getCarID());
            custID.setText(booking.getCustomerID());
            try{
                dateOut.setDate(df.parse(booking.getOutDate()));
                dateReturn.setDate(df.parse(booking.getReturnDate()));
            } catch (ParseException p){
                p.printStackTrace();
            }
            
            Car car = new Car(booking.getCarID());
            model.setText(car.getModel());
            color1.setText(car.getColor());
            plateNo.setText(car.getPlateNo());
            
            Customer cust = new Customer(booking.getCustomerID());
            custName.setText(cust.getCustomerName());
            IC.setText(cust.getCustomerIC());
            email.setText(cust.getCustomerEmail());
            contactNo.setText(cust.getCustomerContact());
            
        } 
        else{
            noResult.setVisible(true);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        ArrayList<String> bookArray = booking.readBooking();
        Boolean flag = true;
        Date inputOut = this.dateOut.getDate();
        Date inputReturn = this.dateReturn.getDate();
        Date dateOut = null;
        Date dateReturn = null;
        for (String book:bookArray){
            try{
                dateOut = df.parse(book.split(";")[3]);
                dateReturn = df.parse(book.split(";")[4]);
            }
            catch(ParseException p){
                 p.printStackTrace();
            }

            //check if the date is not booked or date return is not before date rent out 
            //return false if not passed
            if (inputReturn.before(inputOut)){
                flag = false;
                break;
            }
            else if (custID.getText().equals(book.split(";")[1])&& !email.getText().equals(book.split(";")[0])){
                 if ((inputReturn.equals(dateOut) || inputReturn.equals(dateReturn)) ||(inputReturn.after(dateOut) && inputReturn.before(dateReturn))) 
                 {   
                    flag = false;
                    break;
                }
            }  
        }
        if(flag){
            ArrayList<String> record = new ArrayList<String>();
            record.add(bookID.getText());
            record.add(carID.getText());
            record.add(custID.getText());
            record.add(bookID.getText());
            record.add(df.format(inputOut));
            record.add(df.format(inputReturn));
            record.add("approved");
            booking.modifyBooking(record);
            JOptionPane.showMessageDialog(null, "Record Edited Successfully");
 
        } else {
            JOptionPane.showMessageDialog(null, "The car is already booked on the chosen date.", "Error", ERROR_MESSAGE);
        }

    }//GEN-LAST:event_EditBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date today = new Date();          // TODO add your handling code here:
        PDate.setText(df.format(today));
        booking.setBookingID(bookID.getText());
        if(booking.searchBooking()){
            PBookID.setText(booking.getBookingID());
            rentalDate.setText(booking.getOutDate()+" - "+booking.getReturnDate());
            Date date1 = null;
            Date date2 = null;
            try{
                date1 = df.parse(booking.getOutDate());
                date2 = df.parse(booking.getReturnDate());
            } catch (ParseException pe){
                pe.printStackTrace();
            }
            long daysOfRent = date2.getTime() -date1.getTime();
            daysOfRent = TimeUnit.DAYS.convert(daysOfRent, TimeUnit.MILLISECONDS);
            days.setText(daysOfRent+"");       
            Car car = new Car(booking.getCarID());
            Customer cust = new Customer(booking.getCustomerID());
            PCustName.setText(cust.getCustomerName()+" ("+cust.getCustomerID()+")");
            this.car.setText(car.getColor()+" "+car.getModel()+" ("+car.getCarID()+")");
            int subtotalVal = Integer.parseInt(car.getPrice())* Integer.parseInt(days.getText());
            subtotal.setText(""+subtotalVal);
            double taxVal = subtotalVal * 0.1;
            double total = subtotalVal + taxVal + 250;
            tax.setText(taxVal+"");
            deposit.setText("250.00");
            totalPrice.setText(total+"");       
        } 
        
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        booking.setBookingID(bookID.getText());
        booking.deleteBooking();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed

    private void bookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIDActionPerformed

    private void custNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameActionPerformed

    private void ICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ICActionPerformed

    private void contactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNoActionPerformed

    private void custID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custID1ActionPerformed

    private void dateReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateReturn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateReturn1ActionPerformed

    private void dateOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOut1ActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void plateNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateNoActionPerformed

    private void plateNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateNo1ActionPerformed

    private void color1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_color1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_ManageBooking1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField IC;
    private javax.swing.JTextField PBookID;
    private javax.swing.JTextField PCustName;
    private javax.swing.JTextField PDate;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton SearchBtn1;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JTextField SearchTxt1;
    private javax.swing.JButton approveBtn;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField bookID;
    private javax.swing.JTextField bookID1;
    private javax.swing.JTable bookingTable;
    private javax.swing.JTextField car;
    private javax.swing.JTextField carID;
    private javax.swing.JTextField carID1;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JTextField color;
    private javax.swing.JTextField color1;
    private javax.swing.JTextField contactNo;
    private javax.swing.JTextField contactNo1;
    private javax.swing.JTextField custID;
    private javax.swing.JTextField custID1;
    private javax.swing.JTextField custName;
    private javax.swing.JTextField custName1;
    private com.toedter.calendar.JDateChooser dateOut;
    private javax.swing.JTextField dateOut1;
    private com.toedter.calendar.JDateChooser dateReturn;
    private javax.swing.JTextField dateReturn1;
    private javax.swing.JTextField days;
    private javax.swing.JButton declineBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField deposit;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField ic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlab;
    private javax.swing.JLabel jlab1;
    private javax.swing.JLabel jlab10;
    private javax.swing.JLabel jlab11;
    private javax.swing.JTextField model;
    private javax.swing.JTextField model1;
    private javax.swing.JLabel noResult;
    private javax.swing.JLabel noResult1;
    private javax.swing.JTextField paid;
    private javax.swing.JPanel payPane;
    private javax.swing.JLabel paymentLab;
    private javax.swing.JTable pendingBookingTable;
    private javax.swing.JTextField plateNo;
    private javax.swing.JTextField plateNo1;
    private javax.swing.JButton receiptBtn;
    private javax.swing.JTextField rentalDate;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField totalPrice;
    // End of variables declaration//GEN-END:variables
}
