/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jp_resortroombookingsystem;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255,197,197));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLab = new javax.swing.JLabel();
        addBookingBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        ViewBookingBtn = new javax.swing.JButton();
        ViewReceiptBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLab.setFont(new java.awt.Font("Pristina", 1, 30)); // NOI18N
        menuLab.setText("Welcome back ,  staff!");

        addBookingBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBookingBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        addBookingBtn.setForeground(new java.awt.Color(255, 204, 204));
        addBookingBtn.setText("Add Booking");
        addBookingBtn.setBorder(null);
        addBookingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBookingBtn.setMaximumSize(new java.awt.Dimension(133, 25));
        addBookingBtn.setMinimumSize(new java.awt.Dimension(133, 25));
        addBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        logoutBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 204, 204));
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(null);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        ViewBookingBtn.setBackground(new java.awt.Color(0, 0, 0));
        ViewBookingBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        ViewBookingBtn.setForeground(new java.awt.Color(255, 204, 204));
        ViewBookingBtn.setText("Booking Records");
        ViewBookingBtn.setBorder(null);
        ViewBookingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewBookingBtn.setMaximumSize(new java.awt.Dimension(133, 25));
        ViewBookingBtn.setMinimumSize(new java.awt.Dimension(133, 25));
        ViewBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookingBtnActionPerformed(evt);
            }
        });

        ViewReceiptBtn.setBackground(new java.awt.Color(0, 0, 0));
        ViewReceiptBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        ViewReceiptBtn.setForeground(new java.awt.Color(255, 204, 204));
        ViewReceiptBtn.setText("Payment Records");
        ViewReceiptBtn.setBorder(null);
        ViewReceiptBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewReceiptBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(menuLab, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(addBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(menuLab)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddBooking a = new AddBooking();
        a.setVisible(true);
    }//GEN-LAST:event_addBookingBtnActionPerformed

    private void ViewBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookingBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BookingRecords b = new BookingRecords();
        b.setVisible(true);
    }//GEN-LAST:event_ViewBookingBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SignIn s = new SignIn();
        s.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void ViewReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReceiptBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        receipt r = new receipt();
        r.setVisible(true);
    }//GEN-LAST:event_ViewReceiptBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewBookingBtn;
    private javax.swing.JButton ViewReceiptBtn;
    private javax.swing.JButton addBookingBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel menuLab;
    // End of variables declaration//GEN-END:variables
}
